### ISSUE TITLE
mdast-util-gfm-table not working

### ISSUE THREAD

**Issue by lovekonakona** [syntax-tree/mdast-util-gfm-table#5]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-gfm-table@2.0.0

### Steps to reproduce

https://codesandbox.io/p/sandbox/markdown-c3zq55?file=%2Fsrc%2FApp.js

### Expected behavior

give me the table ast

### Actual behavior

output as paragraph

### Affected runtime and version

mdast-util-from-markdown@2.0.0

**Comment by wooorm** [comment]
read the readme, copy the example: use `micromark-extension-gfm-table`.
